analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - test/**
    - example/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_classes_with_only_static_members
    - avoid_empty_else
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions # under review (see #1068)
    - avoid_relative_lib_imports # under review (see #1068)
    - avoid_renaming_method_parameters # under review (see #1068)
    - avoid_return_types_on_setters
    - avoid_setters_without_getters
    - avoid_single_cascade_in_expression_statements # under review (see #1068)
    - avoid_types_as_parameter_names # under review (see #1068)
    - avoid_unused_constructor_parameters # under review (see #1068)
    - camel_case_types
    - constant_identifier_names
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names # under review (see #1068)
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    # TODO - only_throw_errors
    - overridden_fields
    # TODO    - package_api_docs # not a requirement but a best practice
    - package_names
    - package_prefixed_library_names
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases # under review (see #1068)
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    # TODO - prefer_mixin # when min sdk is 2.1
    - prefer_typing_uninitialized_variables # under review (see #1068)
    - prefer_void_to_null # under review (see #1068)
    # TODO - public_member_api_docs # not a requirement but a best practice
    - recursive_getters
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - type_annotate_public_apis
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new # under review (see #1068)
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis # under review (see #1068)
    - unnecessary_statements # under review (see #1068)
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_setters_to_change_properties
    - use_string_buffers
    - valid_regexps
    - void_checks # under review (see #1068)