name: Analyze

on: [push, pull_request]

jobs:
  analyze:
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    container:
      image: dart:2.18
    
    steps:
    - uses: actions/checkout@master
    - run: dart pub get
    - run: dart analyze --fatal-infos
    - run: dart run tool/reformat.dart
    - run: dart pub publish -n
